### ISSUE TITLE
Help needed?

### ISSUE THREAD

**Issue by bastiankoetsier** [ThreeDotsLabs/watermill-amazonsqs#15]
Hey @m110 , 
I have been enjoying your content and your course (so far 😉 )! At work, we are on the journey to an event-driven-architecture and are leveraging SQS in specific quite a bit. We would really like to test out watermill as the backbone for this architecture but this package seems a bit "underdeveloped" (no offense!). Do you have concrete plans to maintain and support it or is this more something the community should take care of? I am just curious if you are looking for help to maintain/develop this package to bring it to a stable release? Or do you suggest to better fork and maintain in private? 

Greetings from Berlin!

**Comment by Mariscal6** [comment]
Hi @bastiankoetsier! Pls check this PR https://github.com/ThreeDotsLabs/watermill-amazonsqs/pull/14#issuecomment-1906021524

I've been using it for a while and works pretty good for my use case

**Comment by bastiankoetsier** [comment]
@Mariscal6 thanks for the response! I saw the PR but was a bit discouraged/curious about the plans of this package. Hence my question for a "stable"/maintained release of it.

**Comment by m110** [comment]
Hey @bastiankoetsier! We definitely want to support this package in the near future. It would be great to hear feedback from people who use SQS/SNS on production, as we currently don't. :)

**Comment by m110** [comment]
Releasing a stable v1.0.0 is one of our goals for Q1. We're also happy to review contributions (I'm sorry if it takes long - please ping us if we don't reply right away!)

**Comment by m110** [comment]
@roblaszczak is working on v1.0 right now, so I'm closing the issue. :)
